# footer部分的配置。可以不填。
# 对portal-web、mis-web和auth的登录界面有效
footer:

  # 对所有域名生效的footer文本，默认为空字符串
  defaultText: ""

  # 对具体hostname生效的footer文本，可以不填
  # hostnameTextMap:
    # 从a.com的访问显示footer文本为a.com的文本
    # a.com: a.com的文本

# 主题色配置。可以不填
# 对portal-web和mis-web有效
primaryColor:

  # 对所有域名生效的主题色。默认为#94070A
  defaultColor: "#94070A"

  # 对具体hostname生效的生效，可以不填
  # hostnameTextMap:
    # 从a.com的访问的主题色为#000000
    # a.com: "#000000"
