lint:
  rules:
    remove:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - REPEATED_FIELD_NAMES_PLURALIZED

  rules_option:
    max_line_length:
      max_chars: 120
      tab_chars: 2
