# 这个应用的ID
id: jupyter

# 这个应用的名字
name: jupyter

logoPath: /apps/Jupyter.svg

image:
  # 镜像名称
  name: jupyter/minimal-notebook
  # 镜像版本
  tag: latest

# 指定应用类型为web
type: web
# Web应用的配置
web:
  proxyType: absolute
  # 如何连接应用
  connect:
    method: POST
    path: /login
    formData:
      password: "{{ PASSWORD }}"
