# 这个应用的ID
id: vscode

# 这个应用的名字
name: VSCode

# 这个应用的图标文件在公共文件下的路径
# logoPath: /test.svg


image:
  # 镜像名称
  name: codercom/code-server
  # 镜像版本
  tag: 4.20.0

tags:
  - vscode

# 指定应用类型为web
type: web

web:
  # 准备脚本
  beforeScript: |
    export PASSWORD=$(get_password 12)

  # 指明运行任务的脚本中的启动命令，用户在创建应用页面可以在脚本中替换该命令
  startCommand:
    code-server
  # 运行任务的脚本。可以使用准备脚本定义的
  script: |
    PASSWORD=$PASSWORD
    code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password
  proxyType: relative
  # 如何连接应用
  connect:
    method: POST
    path: /login
    formData:
      password: "{{ PASSWORD }}"
