displayName: "hpc01Name"
adapterUrl: 0.0.0.0:6000
loginNodes:
  - name: loginNode01
    address: localhost:22222

# slurm:
#   partitions:
#     - name: compute
#       nodes: 3
#       mem: 262144
#       cores: 32
#       gpus: 0
#       qos:
#         - low
#         - normal
#         - high
#       unit: "cpusAlloc"
#       comment: "说明"

#     - name: GPU
#       nodes: 1
#       mem: 262144
#       cores: 48
#       gpus: 8
#       qos: ["low", "normal", "high"]
#       unit: "gpu"
#       comment: "说明"
