# Copyright (c) 2022 Peking University and Peking University Institute for Computing and Digital Economy
# SCOW is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

version: "3"

services:

  gateway:
    image: $IMAGE_BASE/gateway:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.gateway
      platforms:
        - linux/amd64
        - linux/arm64


  mis-web-mis:
    image: $IMAGE_BASE/mis-web-mis:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.mis-web
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - BASE_PATH=/mis

  mis-web-root:
    image: $IMAGE_BASE/mis-web-root:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.mis-web
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - BASE_PATH=

  portal-web-portal:
    image: $IMAGE_BASE/portal-web-portal:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.portal-web
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - BASE_PATH=/portal

  portal-web-root:
    image: $IMAGE_BASE/portal-web-root:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.portal-web
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - BASE_PATH=

  mis-server:
    image: $IMAGE_BASE/mis-server:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.mis-server
      platforms:
        - linux/amd64
        - linux/arm64

  portal-server:
    image: $IMAGE_BASE/portal-server:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.portal-server
      platforms:
        - linux/amd64
        - linux/arm64

  auth:
    image: $IMAGE_BASE/auth:$TAG
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.auth
      platforms:
        - linux/amd64
        - linux/arm64


