# 集群显示名称
displayName: hpc01

adapterUrl: "172.16.20.124:8999"

loginNodes:
  # 登录节点展示名称
  - name: login
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: 172.16.20.124:2022
