name: Bug Report
description: 提交错误报告来帮助我们改进 | Create a report to help us improve
title: "[Bug/Help] auth: User does not exist when I login"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告！ | Thanks for taking the time to fill out this bug report!
        请为您的issue命名一个好的标题，尽量在标题中注明您的issue相关的模块名称并对问题做简要描述。像这样：
          - `[Bug] portal: 创建Jupyter应用时交互式应用列表报500错误` 或者
          - `[Help] auth: 登录系统时提示用户不存在`
        Please try to give your issue a good title. Try using the app module name related to your issue in the title and a brief description of the problem. Like this:
          - `[Bug] portal: Interactive app list reported 500 error when I created a Jupyter app` or
          - `[Help] auth: User does not exist when I login`
  - type: checkboxes
    attributes:
      label: 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
      description: |
        请先搜索您遇到的错误是否在已有的issues或讨论中提到过。
        Please search to see if an issue / discussion already exists for the bug you encountered.
        [Issues](https://github.com/PKUHPC/SCOW/issues)
        [Discussions](https://github.com/PKUHPC/SCOW/discussions)
      options:
        - label: 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
          required: true
  - type: textarea
    attributes:
      label: 发生了什么 | What happened
      description: |
        描述遇到的情况。
        A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 期望结果 | What did you expect to happen
      description: |
        描述预期的结果。
        A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 之前运行正常吗？ | Did this work before?
      description: |
        如果之前可以运行正常，SCOW是哪个版本？
        If this worked before, what SCOW version worked correctly?
    validations:
      required: false
  - type: textarea
    attributes:
      label: 复现方法 | Steps To Reproduce
      description: |
        复现当前问题的详细步骤。
        Steps to reproduce the bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: 运行环境 | Environment
      description: |
        examples:
          - **OS**: CentOS 7.9
          - **Scheduler**: Slurm 22.05.3
          - **Docker**: 20.10.22
          - **Docker-compose**: v2.7.0
          - **SCOW cli**: v1.1.0
          - **SCOW**: v1.2.1
          - **Adapter**： slurm-adapter v1.1.0
      value: |
        - OS:
        - Scheduler:
        - Docker:
        - Docker-compose:
        - SCOW cli:
        - SCOW:
        - Adapter:
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: 备注 | Anything else?
      description: |
        您可以在这里补充其他关于该问题背景信息的描述、链接或引用等。
        
        您可以通过点击高亮此区域然后拖动文件的方式上传图片或日志文件。
        
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false