# 是否启用作业管理功能
jobManagement: true

# 登录节点桌面功能
loginDesktop:
  # 是否启用
  enabled: true

  wms:
    - name: Xfce
      wm: xfce
    - name: MATE
      wm: mate
    - name: GNOME 3
      wm: ""
    - name: GNOME 2
      wm: 2d
    - name: KDE
      wm: 1-kde-plasma-standard
    - name: cinnamon
      wm: cinnamon

  # 最多启动多少个桌面节点
  maxDesktops: 3

# 是否启用交互式任务功能
apps: true

# 主页标题
homeTitle:
  defaultText: "Super Computing on Web<br/>Test"
  hostnameMap:
    a.com: "a.com's SCOW Deployment"

# 主页文本
homeText:
  defaultText: "SCOW<br/>Haha"
  hostnameMap:
    a.com: "a.com's SCOW"

# 如果部署了管理系统，请设置管理系统部署的路径
# misPath: /mis

# 是否启用终端功能
shell: true
# 提交作业的默认工作目录。使用{name}代替作业名称。相对于用户的家目录
# submitJobDefaultPwd: scow/jobs/{name}

# 将保存的作业保存到什么位置。相对于用户家目录
# savedJobsDir: scow/savedJobs

# 将交互式任务的信息保存到什么位置。相对于用户的家目录
# appJobsDir: scow/appData

# TurboVNC的安装路径
# turboVNCPath: /opt/TurboVNC

# 新增导航链接
# text: 链接名
# url: 链接地址
# icon: 链接显示icon，填入antd icon id form https://ant.design/components/icon-cn
# children: [同样的nav对象，但是不允许再设置children]
# iconSourceUrl?
navLinks:
    - text: "一级导航1"
      url: "https://hahahaha1.com/"
      icon: "icon-tuichu"
      children:
        - text: "二级导航1"
          url: "https://hahahaha1.1.com"
          icon: "icon-facebook"
        - text: "二级导航2"
          url: "https://hahahaha1.2.com"
          icon: "icon-facebook"
    - text: "一级导航2"
      url: "https:////hahahaha2.com"
      icon: "icon-twitter"
      children: []

