FROM node:hydrogen-alpine@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++ git

RUN corepack enable

WORKDIR /app

COPY pnpm-lock.yaml ./
RUN pnpm fetch

COPY package.json pnpm-workspace.yaml .npmrc ./

COPY libs ./libs
COPY apps ./apps

RUN pnpm i --offline --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

RUN pnpm run build

RUN pnpm --filter "./apps/mis-server" --prod deploy dist/mis-server
RUN pnpm --filter "./apps/portal-server" --prod deploy dist/portal-server
RUN pnpm --filter "./apps/auth" --prod deploy dist/auth
RUN pnpm --filter "./apps/portal-web" --prod deploy dist/portal-web
RUN pnpm --filter "./apps/mis-web" --prod deploy dist/mis-web

FROM node:hydrogen-alpine@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b AS runner

ENV NODE_ENV=production

WORKDIR /app
COPY --from=builder /app/dist dist

CMD [ "pnpm" ]



