FROM node:hydrogen-alpine@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

COPY libs/libconfig/package.json ./libs/libconfig/
COPY libs/config/package.json ./libs/config/
COPY libs/decimal/package.json ./libs/decimal/
COPY libs/ssh/package.json ./libs/ssh/
COPY apps/portal-server/package.json ./apps/portal-server/

RUN pnpm i --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/libconfig ./libs/libconfig
COPY libs/config ./libs/config
COPY libs/auth ./libs/auth
COPY libs/decimal ./libs/decimal
COPY libs/ssh ./libs/ssh
COPY apps/portal-server ./apps/portal-server

RUN pnpm run build

RUN rm -rf node_modules && pnpm i --prod --frozen-lockfile --offline

FROM node:hydrogen-alpine@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b AS runner

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/decimal
COPY --from=builder /app/libs/decimal/package.json .
COPY --from=builder /app/libs/decimal/node_modules/ ./node_modules
COPY --from=builder /app/libs/decimal/build/ ./build

WORKDIR /app/libs/libconfig
COPY --from=builder /app/libs/libconfig/package.json .
COPY --from=builder /app/libs/libconfig/node_modules/ ./node_modules
COPY --from=builder /app/libs/libconfig/build/ ./build

WORKDIR /app/libs/ssh
COPY --from=builder /app/libs/ssh/package.json .
COPY --from=builder /app/libs/ssh/node_modules/ ./node_modules
COPY --from=builder /app/libs/ssh/build/ ./build

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/portal-server
COPY --from=builder /app/apps/portal-server/package.json .
COPY --from=builder /app/apps/portal-server/node_modules/ ./node_modules
COPY --from=builder /app/apps/portal-server/build/ ./src
COPY --from=builder /app/apps/portal-server/assets ./assets

ENV NODE_ENV production

ENTRYPOINT [ "node", "src/index.js" ]



