FROM node:16-alpine@sha256:1a9a71ea86aad332aa7740316d4111ee1bd4e890df47d3b5eff3e5bded3b3d10 AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN npm install -g pnpm@7.0.1

WORKDIR /app
COPY pnpm-lock.yaml ./
RUN pnpm fetch

COPY package.json pnpm-workspace.yaml .npmrc ./

COPY libs/config/package.json ./libs/config/
COPY docs/package.json ./docs/

# Must run twice
# First run doesn't create node_modules on libs
RUN pnpm install
RUN pnpm install


COPY tsconfig.json .eslintrc.json ./

COPY libs/config ./libs/config
COPY docs ./docs

ARG BASE_PATH="/"
ENV BASE_PATH=${BASE_PATH}


RUN pnpm run build

FROM nginx:stable-alpine as runner

COPY ./docs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/docs/build /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
