FROM node:gallium-alpine@sha256:554142f9a6367f1fbd776a1b2048fab3a2cc7aa477d7fe9c00ce0f110aa45716 AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./


COPY libs/config/package.json ./libs/config/
COPY libs/decimal/package.json ./libs/decimal/
COPY apps/portal-web/package.json ./apps/portal-web/

RUN pnpm i --frozen-lockfile

RUN apk add git

RUN pnpm run --filter portal-web cloneNoVnc

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY libs/decimal ./libs/decimal
COPY apps/portal-web ./apps/portal-web

ARG BASE_PATH=""
ENV NEXT_PUBLIC_BASE_PATH=$BASE_PATH

RUN pnpm run build

RUN rm -rf node_modules && pnpm i --prod --frozen-lockfile --offline

FROM node:gallium-alpine@sha256:554142f9a6367f1fbd776a1b2048fab3a2cc7aa477d7fe9c00ce0f110aa45716 AS runner

RUN apk add --no-cache openssh-client

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/portal-web
COPY --from=builder /app/apps/portal-web/package.json ./package.json
COPY --from=builder /app/apps/portal-web/node_modules ./node_modules
COPY --from=builder /app/apps/portal-web/next.config.js ./
COPY --from=builder /app/apps/portal-web/config.js ./
COPY --from=builder /app/apps/portal-web/public ./public
COPY --from=builder /app/apps/portal-web/assets ./assets
COPY --from=builder /app/apps/portal-web/api-routes-schemas.json ./api-routes-schemas.json
COPY --from=builder /app/apps/portal-web/.next ./.next

EXPOSE 3000


ENV NODE_ENV production
ARG BASE_PATH=""
ENV NEXT_PUBLIC_BASE_PATH=$BASE_PATH

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "serve"]
