FROM node:gallium-alpine@sha256:1c8769a8c9ed57817ef07162744a3722421333a438185c560aa42a9a1fc6ea23 AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

COPY libs/config/package.json ./libs/config/
COPY apps/docs/package.json ./apps/docs/

RUN pnpm i --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY docs ./docs

ARG BASE_PATH="/"
ENV BASE_PATH=${BASE_PATH}

RUN pnpm run build

FROM nginx:stable-alpine as runner

COPY ./docs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/docs/build /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
