FROM node:16-alpine@sha256:1a9a71ea86aad332aa7740316d4111ee1bd4e890df47d3b5eff3e5bded3b3d10 AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN npm install -g pnpm@7.0.1

WORKDIR /app
COPY pnpm-lock.yaml ./
RUN pnpm fetch

COPY package.json pnpm-workspace.yaml .npmrc ./

COPY libs/config/package.json ./libs/config/
COPY libs/decimal/package.json ./libs/decimal/
COPY apps/mis-web/package.json apps/mis-web/

# Must run twice
# First run doesn't create node_modules on libs
RUN pnpm install --offline
RUN pnpm install --offline

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY libs/decimal ./libs/decimal
COPY apps/mis-web apps/mis-web

ARG BASE_PATH="/"
ENV NEXT_PUBLIC_BASE_PATH=${BASE_PATH}

RUN pnpm run build

RUN rm -rf node_modules && pnpm install -r --prod --offline

FROM node:16-alpine@sha256:1a9a71ea86aad332aa7740316d4111ee1bd4e890df47d3b5eff3e5bded3b3d10 AS runner

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/mis-web
COPY --from=builder /app/apps/mis-web/package.json ./package.json
COPY --from=builder /app/apps/mis-web/node_modules ./node_modules
COPY --from=builder /app/apps/mis-web/next.config.js ./
COPY --from=builder /app/apps/mis-web/config.js ./
COPY --from=builder /app/apps/mis-web/public ./public
COPY --from=builder /app/apps/mis-web/assets ./assets
COPY --from=builder /app/apps/mis-web/api-routes-schemas.json ./api-routes-schemas.json
COPY --from=builder /app/apps/mis-web/.next ./.next

EXPOSE 3000

ENV NODE_ENV production
ARG BASE_PATH=""
ENV NEXT_PUBLIC_BASE_PATH=$BASE_PATH

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "serve"]
