FROM node:16-alpine@sha256:bb776153f81d6e931211e3cadd7eef92c811e7086993b685d1f40242d486b9bb AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN npm install -g pnpm@7.0.1


WORKDIR /app
COPY pnpm-lock.yaml ./
RUN pnpm fetch

COPY package.json pnpm-workspace.yaml .npmrc ./

COPY libs/config/package.json ./libs/config/
COPY apps/clusterops-slurm/package.json ./apps/clusterops-slurm/

# Must run twice
# First run doesn't create node_modules on libs
RUN pnpm install --offline
RUN pnpm install --offline


COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY apps/clusterops-slurm ./apps/clusterops-slurm

RUN pnpm run build

RUN rm -rf node_modules && pnpm install -r --prod --offline

FROM node:16-alpine@sha256:bb776153f81d6e931211e3cadd7eef92c811e7086993b685d1f40242d486b9bb AS runner


WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/clusterops-slurm
COPY --from=builder /app/apps/clusterops-slurm/package.json .
COPY --from=builder /app/apps/clusterops-slurm/node_modules/ ./node_modules
COPY --from=builder /app/apps/clusterops-slurm/build/ ./src


ENV NODE_ENV production
EXPOSE 5000

# Run node directly to support graceful shutdown
ENTRYPOINT [ "node", "src/index.js" ]




