FROM node:gallium-alpine@sha256:4d68856f48be7c73cd83ba8af3b6bae98f4679e14d1ff49e164625ae8831533a AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

COPY libs/auth/package.json ./libs/auth/
COPY libs/config/package.json ./libs/config/
COPY libs/decimal/package.json ./libs/decimal/
COPY apps/mis-web/package.json apps/mis-web/

RUN pnpm i --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY libs/auth ./libs/auth
COPY libs/decimal ./libs/decimal
COPY apps/mis-web apps/mis-web

ARG BASE_PATH=""
ENV NEXT_PUBLIC_BASE_PATH=$BASE_PATH

RUN pnpm run build

RUN rm -rf node_modules && pnpm i --prod --frozen-lockfile --offline

FROM node:gallium-alpine@sha256:4d68856f48be7c73cd83ba8af3b6bae98f4679e14d1ff49e164625ae8831533a AS runner

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/auth
COPY --from=builder /app/libs/auth/package.json .
COPY --from=builder /app/libs/auth/node_modules/ ./node_modules
COPY --from=builder /app/libs/auth/build/ ./build

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/mis-web
COPY --from=builder /app/apps/mis-web/package.json ./package.json
COPY --from=builder /app/apps/mis-web/node_modules ./node_modules
COPY --from=builder /app/apps/mis-web/next.config.js ./
COPY --from=builder /app/apps/mis-web/config.js ./
COPY --from=builder /app/apps/mis-web/public ./public
COPY --from=builder /app/apps/mis-web/assets ./assets
COPY --from=builder /app/apps/mis-web/api-routes-schemas.json ./api-routes-schemas.json
COPY --from=builder /app/apps/mis-web/.next ./.next

EXPOSE 3000

ENV NODE_ENV production
ARG BASE_PATH=""
ENV NEXT_PUBLIC_BASE_PATH=$BASE_PATH

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "serve"]
