FROM node:gallium-alpine@sha256:1fafca8cf41faf035192f5df1a5387656898bec6ac2f92f011d051ac2344f5c9 AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY libs/config/package.json ./libs/config/
COPY apps/clusterops-slurm/package.json ./apps/clusterops-slurm/

RUN pnpm i --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY apps/clusterops-slurm ./apps/clusterops-slurm

RUN pnpm run build

RUN rm -rf node_modules && pnpm i --prod --frozen-lockfile --offline

FROM node:gallium-alpine@sha256:1fafca8cf41faf035192f5df1a5387656898bec6ac2f92f011d051ac2344f5c9 AS runner

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/clusterops-slurm
COPY --from=builder /app/apps/clusterops-slurm/package.json .
COPY --from=builder /app/apps/clusterops-slurm/node_modules/ ./node_modules
COPY --from=builder /app/apps/clusterops-slurm/build/ ./src


ENV NODE_ENV production
EXPOSE 5000

# Run node directly to support graceful shutdown
ENTRYPOINT [ "node", "src/index.js" ]




