FROM node:gallium-alpine@sha256:c785e617c8d7015190c0d41af52cc69be8a16e3d9eb7cb21f0bb58bcfca14d6b AS builder

RUN apk update && apk add libc6-compat python3 make gcc g++

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY libs/config/package.json ./libs/config/
COPY apps/job-server-slurm/package.json ./apps/job-server-slurm/

RUN pnpm i --frozen-lockfile

COPY tsconfig.json .eslintrc.json ./

COPY protos ./protos

COPY libs/config ./libs/config
COPY apps/job-server-slurm ./apps/job-server-slurm

RUN pnpm run build

RUN rm -rf node_modules && pnpm i --prod --frozen-lockfile --offline

FROM node:gallium-alpine@sha256:c785e617c8d7015190c0d41af52cc69be8a16e3d9eb7cb21f0bb58bcfca14d6b AS runner

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/libs/config
COPY --from=builder /app/libs/config/package.json .
COPY --from=builder /app/libs/config/node_modules/ ./node_modules
COPY --from=builder /app/libs/config/build/ ./build

WORKDIR /app/apps/job-server-slurm
COPY --from=builder /app/apps/job-server-slurm/assets ./assets
COPY --from=builder /app/apps/job-server-slurm/package.json .
COPY --from=builder /app/apps/job-server-slurm/node_modules/ ./node_modules
COPY --from=builder /app/apps/job-server-slurm/build ./src

# Serve
EXPOSE 5000

ENV NODE_ENV production

# Run node directly to support graceful shutdown
ENTRYPOINT [ "node", "--preserve-symlinks", "src/index.js" ]

