FROM nginx:alpine@sha256:7d003b925548b52a107073c359f69ed1f2113109891dd63cd007f1a4365c9d51

# load njs
RUN sed -i "1 i\load_module /etc/nginx/modules/ngx_http_js_module.so;\n" /etc/nginx/nginx.conf

COPY apps/gateway/includes /etc/nginx/includes
COPY apps/gateway/js /etc/nginx/js
COPY apps/gateway/nginx.conf /etc/nginx/templates/default.conf.template


ENV CLIENT_MAX_BODY_SIZE=1g
ENV ACCESS_LOG=/var/log/nginx/access.log
ENV ERROR_LOG=/var/log/nginx/error.log
ENV EXTRA=
ENV FILE_SERVERS=
ENV ROOT_PATH_INTERNAL_URL=http://portal-web:3000
ENV SUB_PATH_INTERNAL_URL=http://mis-web:3000
ENV SUB_PATH=/mis
ENV SHELL_SERVER_INTERNAL_URL=http://shell-server:5000
ENV AUTH_INTERNAL_URL=http://auth:5000
ENV RESOLVER=127.0.0.11
