# 是否启用作业管理功能
jobManagement: true

# 是否启用交互式任务功能
apps: true

loginDesktop:
  # 是否启用桌面功能
  enabled: true

  # 桌面
  wms:
    - name: Xfce
      wm: xfce

# TurboVNC的安装路径
turboVNCPath: /opt/TurboVNC

# 主页标题
homeTitle:
  defaultText: "Super Computing on Web"

# 主页文本
homeText:
  defaultText: "SCOW"

# 是否启用终端功能
shell: true
