# 这个应用的ID
id: vscode

# 这个应用的名字
name: VSCode

# 这个应用的图标文件在公共文件下的路径
# logoPath: /test.svg

# 指定应用类型为web
type: web

web:
  # 准备脚本
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)
  # 运行任务的脚本。可以使用准备脚本定义的
  script: |
    PASSWORD=$PASSWORD /data/software/code-server/bin/code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password
  proxyType: relative
  # 如何连接应用
  connect:
    method: POST
    path: /login
    formData:
      password: "{{ PASSWORD }}"


# 配置HTML表单，用户可以指定code-server版本
attributes:
  - type: select
    name: selectVersion
    label: 选择版本
    # label:
    #   i18n:
    #     default: 选择版本
    #     en: Select Version
    #     zh_cn: 选择版本
    required: true  # 用户必须选择一个版本
    placeholder: 选择code-server的版本  # 提示信息
    # placeholder:
    #   i18n:
    #     default: 选择code-server的版本
    #     en: Choose the version of the code-server
    #     zh_cn: 选择code-server的版本
    select:
      - value: code-server/4.8.0
        label: version 4.8.0
      - value: code-server/4.9.0
        label: version 4.9.0

  - type: text
    name: sbatchOptions
    label: 其他sbatch参数
    # label:
    #   i18n:
    #     default: 其他sbatch参数
    #     en: Other sbatch parameters
    #     zh_cn: 其他sbatch参数
    required: false
    placeholder: "比如：--gpus gres:2 --time 10"
    # placeholder:
    #   i18n:
    #     default: "比如：--gpus gres:2 --time 10"
    #     en: "For example: --gpus gres:2 --time 10"
    #     zh_cn: "比如：--gpus gres:2 --time 10"
    # 如果将sbatchOptions配置为固定值
    # fixedValue:
    #   value: "--time 10"
    #   hidden: false

  # type为file的HTML表单配置
  # 需使用对应环境变量名称fileDirectory
  # - type: file
  #   name: fileDirectory
  #   label: vscode文件目录
  #   required: false
  #   placeholder: 选择vscode文件
  #   defaultValue: /data/home/demo_admin


# 配置系统保留HTML表单项的固定值，其中 maxTime 配置数值单位为分钟
# reservedAppAttributes:
#   - name: account
#     fixedValue:
#       value: a_abcd
#       hidden: false
#   - name: partition
#     fixedValue:
#       value: normal
#   - name: qos
#     fixedValue:
#       value: normal
#       hidden: true
#   - name: nodeCount
#     fixedValue:
#       value: 1
#   - name: coreCount
#     fixedValue:
#       value: 1
#   - name: maxTime
#     fixedValue:
#       value: 10

