id: vscode
name: VSCode
type: web

slurm:
  options:
    - "-x node[1-2]"

web:
  proxyType: relative
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)
  script: |
    PASSWORD=$PASSWORD code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password
  connect:
    method: POST
    path: /login
    formData:
      password: "{PASSWORD}"


attributes:
  - type: text
    key: version
    label: 版本
  - type: number
    key: size
    label: 数量
  - type: select
    key: selectVersion
    label: 选择版本
    select:
      - key: v10
        value: v10
      - key: v11
        value: v11
