id: vscode
name: VSCode
type: web
proxy_type: rproxy

slurm:
  options:
    - "-x node[1-2]"

web:
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)
  script: |
    PASSWORD=$PASSWORD code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password
  connect:
    method: POST
    path: /login
    formData:
      password: "{PASSWORD}"
