# 集群显示名称
displayName: hpc01Name

# 指定slurm配置
slurm:
  # 各个登录节点的IP或者域名，服务节点必须可访问
  loginNodes:
    - login01
    - login02

  # 集群的分区信息
  partitions:
    # 分区1的名字, 不能包含空格
    - name: compute
      # 分区内节点数
      nodes: 28
      # 单节点内存数量，单位M
      mem: 7500
      # 核心数
      cores: 2
      # GPU卡数
      gpus: 0
      # QOS
      qos:
        - low
        - normal
        - high
      # 这个分区的备注信息
      comment: ""

    - name: GPU
      nodes: 1
      mem: 262144
      cores: 48
      gpus: 8
      qos:
        - low
        - normal
        - high
      comment: ""

  # 如果这个集群要部署管理系统，请增加以下配置
  # 如果不需要，将整个mis块注释掉
  mis:
    # 部署slurm.sh的机器的地址
    managerUrl: haha
    # slurm.sh在机器中的绝对地址
    scriptPath: /test/slurm.sh

    # 部署slurm.sh的机器通过什么地址访问slurm的数据库
    # 不填写为下面的默认值
    # dbHost: localhost

    # 部署slurm.sh的机器通过什么端口访问slurm的数据库
    # 不填写为下面的默认值
    # dbPort: 3306

    # slurm数据库的用户名
    # 参考slurmdbd.conf的StorageUser配置
    # 不填写为下面的默认值
    # dbUser: root

    # slurmdbd的数据库用户的密码
    # 参考slurmdbd.conf的StoragePass配置
    dbPassword: password

    # slurm accounting数据库的数据库名
    # 参考slurmdbd.conf的StorageLoc配置
    # 不填写为下面的默认值
    # slurmAcctDbName: "slurm_acct_db"

    # 这个集群在slurm中的集群名字
    clusterName: pkuhpc
