# 管理系统数据库的信息。
# 如果直接使用scow-deployment提供的数据库，此部分内容不修改
db:
  host: db
  port: 3306
  user: root
  dbName: scow

# 获取作业相关配置
fetchJobs:
  # 源作业信息数据库的数据库信息
  db:
    host: sourcedb
    port: 3307
    user: root
    password: jobtablepassword
    dbName: jobs
    tableName: jobs
    # 数据库类型，可选mariadb或者mysql
    # 默认为mariadb
    # type: mariadb

  # 周期性获取数据
  periodicFetch:
    # 是否开启
    enabled: true
    # 周期的cron表达式
    cron: "10 */10 * * * *"

# 预定义的充值类型
predefinedChargingTypes:
  - 测试

# 创建账户时，账户名的规则。不设置就没有限制
# accountNamePattern:
  # 正则表达式
  # regex: ""

  # 出错时的消息
  # errorMessage: ""

# 创建用户相关配置
# createUser:

  # 是否启用从SCOW中创建用户
  # enabled: true

  # 创建用户时，用户ID的规则。不设置就没有限制
  # userIdPattern:
    # 正则表达式
    # regex: ""

    # 出错时的消息
    # errorMessage: ""
