# 这个应用的ID
id: vscode

# 这个应用的名字
name: VSCode

logoPath: apps/vscode.png

# 指定应用类型为web
type: web
# 可以运行这个应用的节点地址。
# 如果不设置nodes，则所有节点都可以运行
#nodes:
#  - cn1
#  - cn2
#  - cn3
#  - cn4

# Web应用的配置
web:
  # 准备脚本
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)

  # 运行任务的脚本。可以使用准备脚本定义的
  script: |
    PASSWORD=$PASSWORD /data/software/code-server/bin/code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password
  proxyType: relative
  # 如何连接应用
  connect:
    method: POST
    path: /login
    formData:
      password: "{{ PASSWORD }}"
