version: '3'
services:
  gateway:
    restart: unless-stopped
    environment:
      - SCOW_LAUNCH_APP=gateway
      - BASE_PATH=
      - PORTAL_PATH=/
      - MIS_PATH=/
    ports:
      - '80:80'
    image: ghcr.io/pkuhpc/scow/scow:master
    volumes:
      - /etc/hosts:/etc/hosts
  redis:
    restart: unless-stopped
    environment: []
    ports: []
    image: redis:alpine
    volumes: []
  auth:
    restart: unless-stopped
    environment: []
    ports: []
    image: ghcr.io/pkuhpc/scow/auth:master
    volumes:
      - /etc/hosts:/etc/hosts
      - ./config:/etc/scow
      - ~/.ssh:/root/.ssh
  mis-server:
    restart: unless-stopped
    environment:
      - SCOW_LAUNCH_APP=mis-server
      - DB_PASSWORD=must!chang3this
      - LOG_LEVEL=info
      - LOG_PRETTY=false
    ports: []
    image: ghcr.io/pkuhpc/scow/scow:master
    volumes:
      - /etc/hosts:/etc/hosts
      - ./config:/etc/scow
      - ~/.ssh:/root/.ssh
  mis-web:
    restart: unless-stopped
    environment:
      - SCOW_LAUNCH_APP=mis-web
      - BASE_PATH=/
      - PORTAL_URL=/
      - PORTAL_DEPLOYED=false
      - AUTH_EXTERNAL_URL=/auth
    ports: []
    image: ghcr.io/pkuhpc/scow/scow:master
    volumes:
      - ./config:/etc/scow
  db:
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=must!chang3this
    ports: []
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
