db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_ai

url: localhost:5007

harborConfig:
  url: 10.129.227.64
  project: test
  user: admin
  password: icode@2023CS
