db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_ai

url: localhost:5007

harborConfig:
  registryUrl: http://10.129.227.64/harbor/projects/2/repositories/test/
  loginUser: admin
  loginPassword: icode@2023CS
