# 这个应用的ID
id: emacs

# 这个应用的名字
name: emacs

# 指定应用类型，vnc或者web
type: vnc

# 可以运行这个应用的节点地址
# 如果不设置nodes，则所有节点都可以运行
# nodes:
#   - t001
#   - t002

# VNC应用的配置
vnc:
  # 此X Session的xstartup脚本
  xstartup: |
    emacs -mm

# Web应用的配置
web:
  # 准备脚本
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)

  # 运行任务的脚本。可以使用准备脚本定义的
  script: |
    PASSWORD=$PASSWORD code-server -vvv --bind-addr 0.0.0.0:$PORT --auth password

  # 如何连接应用
  connect:
    method: POST
    path: /login
    formData:
      password: "{{ PASSWORD }}"
