name: Lint PR Title and Content
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:

  lint-title:
    runs-on: ${{ vars.ACTION_RUNNER_LABEL }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
