name: Remove PR artifacts
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  delete-scow-vagrant:
    name: Delete scow-vagrant PR branch
    if: vars.PUSH_VAGRANT == 'true'
    runs-on: ${{ vars.ACTION_RUNNER_LABEL }}
    steps:
      - name: Delete scow-vagrant PR branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.SCOW_DEPLOYMENT_PAT }}
          owner: ${{ vars.VAGRANT_REPO_OWNER }}
          repository: ${{ vars.VAGRANT_REPO_NAME }}
          branches: ${{ github.event.number }}/merge
          soft_fail: true
