name: Cleanup after PR merge

on:
  pull_request:
    types: ["closed"]
    branches: [master]

jobs:
  clean-deployment-branch:
    name: Delete scow-deployment PR branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete scow-deployment PR branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.SCOW_DEPLOYMENT_PAT }}
          owner: PKUHPC
          repository: scow-deployment
          branches: ${{ github.event.number }}/merge
