name: Update scow-deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Push deploy/ to scow-deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pushes to scow-deployment repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./deploy
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          external_repository: PKUHPC/scow-deployment
          publish_branch: ${{ github.ref_name }}
