name: Update side projects

on:
  push:
    tags: ["**"]
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VAGRANT_ORG: PKUHPC
  VAGRANT_REPO: scow-vagrant

jobs:

  openscow-vagrant-check:
    name: Check if the user has write permission to vagrant repo
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      has_write_permission: ${{ steps.check-permission.outputs.result }}
    steps:

      - name: Check if the user has write permission to ${{ env.VAGRANT_ORG }}/${{ env.VAGRANT_REPO }}
        id: check-permission
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { permission } } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: '${{ env.VAGRANT_ORG }}',
              repo: '${{ env.VAGRANT_REPO }}',
              username: context.actor,
            });

            console.log(`The user has ${permission} permission to ${env.VAGRANT_ORG}/${env.VAGRANT_REPO}`);

            return permission === 'admin' || permission === 'write';


  openscow-vagrant:
    name: Update openscow-vagrant
    runs-on: ubuntu-latest

    needs: openscow-vagrant-check
    if: needs.openscow-vagrant-check.outputs.has_write_permission == 'true'

    steps:

      - uses: actions/checkout@v4

      - name: Create version file for tag commit
        if: github.ref_type == 'tag'
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./deploy/vagrant/VERSION"
          FILE_DATA: "${{ github.ref_name }}"

      - name: Pushes to ${{ env.VAGRANT_ORG }}/${{ env.VAGRANT_REPO }} repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.SCOW_DEPLOYMENT_PAT }}
          folder: ./deploy/vagrant
          repository-name: ${{ env.VAGRANT_ORG }}/${{ env.VAGRANT_REPO }}
          branch: ${{ github.ref_type == 'branch' && github.ref_name || 'master' }}
